import { ConnectButton } from "@rainbow-me/rainbowkit"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import DrawerCard from "@/components/DrawerCard"

import dynamic from "next/dynamic"

// 使用 dynamic 导入 Google 地图组件，以确保只在客户端加载
const Map = dynamic(() => import("../components/Map"), {
  loading: () => <p>Loading Map...</p>,
  ssr: false // 禁止在服务器端渲染
})

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dapp Forge</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        {/* <ConnectButton /> */}
        <div style={{ display: "flex", height: "100vh" }}>
          <div style={{ flex: 1 }}>
            {/* 主页面内容，包括地图 */}
            <Map />
          </div>
          {/* 右侧抽屉 */}
          <DrawerCard />
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  )
}

export default Home
